services:
  - type: web
    name: sanawell-twa-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: WEBAPP_URL
        sync: false
      - key: DB_PATH
        value: ./backend/data/sanawell.db
      - key: BOT_MODE
        value: polling
      - key: NODE_VERSION
        value: 24.20.0
